"""add sender_name and memo to payments_raw

Revision ID: d4a311607f35
Revises: 246b638146e4
Create Date: 2026-01-06 20:10:30.889663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4a311607f35'
down_revision: Union[str, None] = '246b638146e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments_raw', sa.Column('sender_name', sa.String(length=255), nullable=True))
    op.add_column('payments_raw', sa.Column('memo', sa.Text(), nullable=True))
    op.add_column('payments_raw', sa.Column('gmail_id', sa.String(length=255), nullable=True))
    op.add_column('payments_raw', sa.Column('received_at', sa.DateTime(), nullable=True))
    op.alter_column('payments_raw', 'sender_identifier',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('payments_raw', 'email_id')
    op.drop_column('payments_raw', 'email_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments_raw', sa.Column('email_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('payments_raw', sa.Column('email_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('payments_raw', 'sender_identifier',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('payments_raw', 'received_at')
    op.drop_column('payments_raw', 'gmail_id')
    op.drop_column('payments_raw', 'memo')
    op.drop_column('payments_raw', 'sender_name')
    # ### end Alembic commands ###
